# Generated by Django 5.2.7 on 2025-10-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('successful_sends', models.IntegerField(default=0)),
                ('failed_sends', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_stats',
            },
        ),
        migrations.CreateModel(
            name='MessageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('user_login', models.CharField(max_length=150)),
                ('content_length', models.IntegerField()),
                ('sent_to_rabbitmq', models.BooleanField(default=False)),
                ('processing_time_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message_analytics',
                'indexes': [models.Index(fields=['user_login', '-created_at'], name='message_ana_user_lo_d5d1e5_idx'), models.Index(fields=['created_at'], name='message_ana_created_e1d466_idx')],
            },
        ),
    ]
