# Generated by Django 5.2.7 on 2025-10-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_to_rabbitmq',
            new_name='sent_to_mq',
        ),
    ]
